export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ORDER_PRODUCT = 'ORDER_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const DISPATCH_PRODUCT = 'DISPATCH_PRODUCT';
export const CANCEL_PRODUCT = 'CANCEL_PRODUCT';
export const EDIT_ORDER_PRODUCT = 'EDIT_ORDER_PRODUCT';
export const REVIEW_PRODUCT='REVIEW_PRODUCT';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';

export const REVIEW_VENDOR='REVIEW_VENDOR';
export const USERS_ERROR='USERS_ERROR';

